service: dictionary-bot

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /webhook
          method: POST
        authorizer:
            required: flase
package:
  individually: true 
  exclude:
    - node_modules/**
