service: dictionary-meaning

provider:
  name: aws
  runtime: nodejs18.x
functions:
  app:
    handler: index.handler
    events:
      - http:
          path: webhook
          method: POST
package:
  individually: true 
  exclude:
    - node_modules/**
